### ISSUE TITLE
Convert to QBCore

### ISSUE THREAD

**Issue by Edvo1901** [ESX-Brasil/esx_gym#2]
Hi Brasil,

I am want to ask for your permission to convert this script to QBCore, is it okay for u? Ofc i will credit your repo and your name in the new script.

Hope you wont find this message annoying as I cant find your discord anywhere on the repos.

Cheers.

**Comment by psycodeliccircus** [comment]
> Hi Brasil,
> 
> I am want to ask for your permission to convert this script to QBCore, is it okay for u? Ofc i will credit your repo and your name in the new script.
> 
> Hope you wont find this message annoying as I cant find your discord anywhere on the repos.
> 
> Cheers.

 OK friend.
The code is free only from credits.
